@startuml
skinparam titleFontSize 30
title **AopProxy 相关结构图**

interface AopProxy {
    + getProxy(): Object
    + getProxy(classLoader: ClassLoader): Object
}

class CglibAopProxy implements AopProxy
class ObjenesisCglibAopProxy extends CglibAopProxy

interface AopProxyFactory {
    createAopProxy(config: AdvisedSupport): AopProxy
}

AopProxyFactory o-right-> AopProxy :create

class AdvisedSupport extends ProxyConfig

AopProxyFactory .up.> AdvisedSupport :according to

class DefaultAopProxyFactory implements AopProxyFactory

class JdkDynamicAopProxy implements AopProxy

interface InvocationHandler
JdkDynamicAopProxy ..|> InvocationHandler

skinparam footerFontSize 20
footer ''地瓜哥''博客网 · https://www.diguage.com · 出品
@enduml