@startuml
header D瓜哥 · ""https://www.diguage.com""

title **PropertyResolver 继承体系**
' 删除去不必要的某些类

interface PropertyResolver

interface ConfigurablePropertyResolver extends PropertyResolver

abstract class AbstractPropertyResolver implements ConfigurablePropertyResolver

class PropertySourcesPropertyResolver extends AbstractPropertyResolver

interface Environment extends PropertyResolver

interface ConfigurableEnvironment extends Environment, ConfigurablePropertyResolver

interface ConfigurableWebEnvironment extends ConfigurableEnvironment

abstract class AbstractEnvironment implements ConfigurableEnvironment

class StandardEnvironment extends AbstractEnvironment

class StandardServletEnvironment extends StandardEnvironment implements ConfigurableWebEnvironment

footer D瓜哥 · ""https://www.diguage.com"" · 出品
@enduml
