@startuml
header D瓜哥 · ""https://www.diguage.com""

title **ApplicationContext 继承体系**


interface BeanFactory
interface HierarchicalBeanFactory
interface ListableBeanFactory

BeanFactory <|-- HierarchicalBeanFactory
BeanFactory <|-- ListableBeanFactory

ListableBeanFactory <|-- ApplicationContext
HierarchicalBeanFactory <|-- ApplicationContext

interface ConfigurableApplicationContext extends ApplicationContext
interface WebApplicationContext extends ApplicationContext
abstract class AbstractApplicationContext implements ConfigurableApplicationContext
abstract class AbstractRefreshableApplicationContext extends AbstractApplicationContext
interface ConfigurablePortletApplicationContext extends WebApplicationContext, ConfigurableApplicationContext
abstract class AbstractRefreshableConfigApplicationContext extends AbstractRefreshableApplicationContext
interface ConfigurableWebApplicationContext extends WebApplicationContext, ConfigurableApplicationContext
class GenericApplicationContext extends AbstractApplicationContext
abstract class AbstractRefreshablePortletApplicationContext extends AbstractRefreshableConfigApplicationContext implements WebApplicationContext, ConfigurablePortletApplicationContext
class StaticPortletApplicationContext extends StaticApplicationContext implements ConfigurablePortletApplicationContext
abstract class AbstractRefreshableWebApplicationContext extends AbstractRefreshableConfigApplicationContext implements ConfigurableWebApplicationContext
abstract class AbstractXmlApplicationContext extends AbstractRefreshableConfigApplicationContext
class StaticWebApplicationContext extends StaticApplicationContext implements ConfigurableWebApplicationContext
class GenericWebApplicationContext extends GenericApplicationContext implements ConfigurableWebApplicationContext
class GenericXmlApplicationContext extends GenericApplicationContext
class AnnotationConfigApplicationContext extends GenericApplicationContext
class XmlPortletApplicationContext extends AbstractRefreshablePortletApplicationContext
class ComplexPortletApplicationContext extends StaticPortletApplicationContext
class XmlWebApplicationContext extends AbstractRefreshableWebApplicationContext
class GroovyWebApplicationContext extends AbstractRefreshableWebApplicationContext
class AnnotationConfigWebApplicationContext extends AbstractRefreshableWebApplicationContext
class ClassPathXmlApplicationContext extends AbstractXmlApplicationContext
class FileSystemXmlApplicationContext extends AbstractXmlApplicationContext
class ComplexWebApplicationContext extends StaticWebApplicationContext
class SimpleWebApplicationContext extends StaticWebApplicationContext


footer D瓜哥 · ""https://www.diguage.com"" · 出品
@enduml